# fly.toml app configuration file generated for pokedex-fullstackopen23part11 on 2023-10-02T20:33:22+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pokedex-fullstackopen23part11"
primary_region = "sin"

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

[build]
  [build.args]
    NODE_VERSION = "16.19.1"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
