name: Testing stuff

on:
  push:
    branches:
      - render_deployment_pull

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: ref_name tag
        env: 
          BRANCH_NAME: ${{toJson(github.ref_name)}}
        run: echo "$BRANCH_NAME"
  randomly-failing-job:
    needs: [a_test_job]
    runs-on: ubuntu-latest      
    steps:
      - id: checkout
        uses: actions/checkout@v2
      - name: Generate 0 or 1
        id: generate_number
        run:  echo "random_number=$(($RANDOM % 2))" >> $GITHUB_OUTPUT
      - name: Pass or fail
        run: |
          if [[ ${{ steps.generate_number.outputs.random_number }} == 0 ]]; then exit 0; else exit 1; fi
      - name: need context messages
        env:
          NEED_CONTEXT: ${{toJson(needs.a_test_job)}}
        run: echo "$NEED_CONTEXT"
      
    